**Creation of ndarray**

1. Write python code to create 3d array in different ways with 15 elements.
2. Array Creation:
a. Create a 4D NumPy array containing the first 12 positive integers as arr1.
b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.
3. Find all attributes of array1 and array2
4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.


**Array Slicing and Indexing:**

a. Creating Arrays:
      - Create a 1-dimensional NumPy array  arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29].
      - Create a 2-dimensional NumPy array  arr2  with the values  [[0, 1, 2], [3, 4, 5], [6, 7, 8]].
      
 b.Basic Indexing:
      - Print the element at index 3 of  arr1.
      - Print the element at row 2, column 1 of  arr2

   c. Array Slicing:
      - Print the first five elements of `arr1`.
      - Print the subarray of `arr2` consisting of the last two rows and the first two columns.
       - Print every second element starting from index 1 up to index 7 of `arr1`.







**Data Type Manipulation**

a. Creating Arrays with Specific Data Types:
      - Create a 1-dimensional NumPy array `int_array` with the values `[1, 2, 3, 4, 5]` and the data type `int16`.
      - Create a 1-dimensional NumPy array `float_array` with the values `[0.1, 0.2, 0.3, 0.4, 0.5]` and the data type `float64`.
      
b. Data Type Conversion:
      - Convert the `float_array` to an array with data type `int32`. Print the result.
      - Convert the `int_array` to an array with data type `float32`. Print the result.

**Generating Random Numbers:**

1.	Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

2.	Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

3.	Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

4.	Apply descriptive statistics for rand_matrix.


**Analyze the Data:**

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]




Describe the data using numpy array.
Measure the following:
1.	How many employees are getting more less than 50000?

2.	Is it following Normal Distribution?

3.	What is the median salary?

4.	What is the range of salaries for this company?

5.	Find the salaries between average salary and 75% of salaries?

6.	How many employees are getting less than 25 % of salaries ?



In [1]:
import numpy as np

In [6]:
n = np.array([[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]])
n

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [4]:
n = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],ndmin = 3)
n

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [5]:
n.reshape(1,3,5)
n

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [8]:
n = np.arange(1,16).reshape(1,3,5)
n

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [11]:
arr1 = np.arange(1,13).reshape(1,1,4,3)
arr1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [15]:
array1 = np.random.rand(20).reshape(1,4,5)

In [16]:
array1

array([[[0.05959717, 0.97272463, 0.61320594, 0.50445792, 0.18587634],
        [0.1309249 , 0.75917152, 0.95083891, 0.25919568, 0.04684774],
        [0.1469572 , 0.86930595, 0.51815146, 0.0052648 , 0.90098012],
        [0.79586987, 0.65483381, 0.17658876, 0.52256123, 0.91131303]]])

### Attributes of arr1

In [23]:
arr1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [18]:
arr1.ndim

4

In [19]:
arr1.size

12

In [20]:
arr1.itemsize

4

In [21]:
arr1.nbytes

48

In [22]:
arr1.dtype


dtype('int32')

### Attributes of array1

In [25]:
array1

array([[[0.05959717, 0.97272463, 0.61320594, 0.50445792, 0.18587634],
        [0.1309249 , 0.75917152, 0.95083891, 0.25919568, 0.04684774],
        [0.1469572 , 0.86930595, 0.51815146, 0.0052648 , 0.90098012],
        [0.79586987, 0.65483381, 0.17658876, 0.52256123, 0.91131303]]])

In [26]:
array1.ndim

3

In [27]:
array1.size

20

In [28]:
array1.itemsize

8

In [29]:
array1.nbytes

160

In [30]:
array1.dtype

dtype('float64')

### Descriptive Statistics on arr1

In [31]:
arr1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [32]:
arr1.mean()

6.5

In [34]:
np.median(arr1)

6.5

In [35]:
arr1.var()

11.916666666666666

In [36]:
arr1.std()

3.452052529534663

In [41]:
range = arr1.max()-arr1.min()
range

11

In [43]:
q1 = np.percentile(arr1,25)

In [44]:
q3 = np.percentile(arr1,75)

In [45]:
IQR = q3-q1

In [46]:
lower = q1 - (1.5*IQR)
upper = q3 + (1.5*IQR)


In [47]:
arr1[arr1<lower]

array([], dtype=int32)

In [48]:
arr1[arr1>upper]

array([], dtype=int32)

### Descriptive Statistics on array1

In [49]:
array1

array([[[0.05959717, 0.97272463, 0.61320594, 0.50445792, 0.18587634],
        [0.1309249 , 0.75917152, 0.95083891, 0.25919568, 0.04684774],
        [0.1469572 , 0.86930595, 0.51815146, 0.0052648 , 0.90098012],
        [0.79586987, 0.65483381, 0.17658876, 0.52256123, 0.91131303]]])

In [50]:
array1.mean()

0.4992333491262487

In [51]:
np.median(array1)

0.5203563473401025

In [53]:
range = array1.max()-array1.min()
range

0.9674598331916122

In [54]:
array1.var()

0.11257973159926322

In [56]:
array1.std()

0.3355290324238176

In [57]:
q1 = np.percentile(array1,25)

In [58]:
q2 = np.percentile(array1,75)

In [59]:
IQR = q3-q1

In [60]:
lower = q1 - (1.5*IQR)
upper = q3 + (1.5*IQR)
arr1[arr1<lower]

array([], dtype=int32)

In [61]:
arr1[arr1>upper]

array([], dtype=int32)

**Array Slicing and Indexing:**

a. Creating Arrays:
      - Create a 1-dimensional NumPy array  arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29].
      - Create a 2-dimensional NumPy array  arr2  with the values  [[0, 1, 2], [3, 4, 5], [6, 7, 8]].
      
 b.Basic Indexing:
      - Print the element at index 3 of  arr1.
      - Print the element at row 2, column 1 of  arr2

   c. Array Slicing:
      - Print the first five elements of `arr1`.
      - Print the subarray of `arr2` consisting of the last two rows and the first two columns.
       - Print every second element starting from index 1 up to index 7 of `arr1`.

In [65]:
arr1 = np.array([0, 11, 26, 73, 42, 51, 6,77, 8,29])
arr1

array([ 0, 11, 26, 73, 42, 51,  6, 77,  8, 29])

In [66]:
arr2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
arr1[3]

73

In [67]:
arr2[2][1]

7

In [69]:
arr1[:5]

array([ 0, 11, 26, 73, 42])

In [73]:
arr2[1:,0:2]

array([[3, 4],
       [6, 7]])

In [74]:
arr1[1:8]

array([11, 26, 73, 42, 51,  6, 77])

**Data Type Manipulation**

a. Creating Arrays with Specific Data Types:
      - Create a 1-dimensional NumPy array `int_array` with the values `[1, 2, 3, 4, 5]` and the data type `int16`.
      - Create a 1-dimensional NumPy array `float_array` with the values `[0.1, 0.2, 0.3, 0.4, 0.5]` and the data type `float64`.
      
b. Data Type Conversion:
      - Convert the `float_array` to an array with data type `int32`. Print the result.
      - Convert the `int_array` to an array with data type `float32`. Print the result.


In [75]:
n = np.array([1, 2, 3, 4, 5],dtype = "int16")

In [76]:
n.dtype

dtype('int16')

In [81]:
n = np.array([0.1, 0.2, 0.3, 0.4, 0.5],dtype = "float64")

In [82]:
n.dtype

dtype('float64')

In [88]:
num = np.array([0.1, 0.2, 0.3, 0.4, 0.5],dtype = "int32")
num.dtype

dtype('int32')

In [86]:
num = np.array([1, 2, 3, 4, 5],dtype = "float32")
num

array([1., 2., 3., 4., 5.], dtype=float32)

**Generating Random Numbers:**

1.	Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

2.	Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

3.	Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

4.	Apply descriptive statistics for rand_matrix.

In [94]:
n = np.random.randint(0,101,10)
n

array([15, 27, 95, 64, 35, 85,  5, 20,  3, 91])

In [95]:
np.random.uniform(-1,1,5)

array([0.03329207, 0.0432081 , 0.19900454, 0.67612911, 0.46667297])

In [101]:
rand_matrix = np.random.randint(50,101,16).reshape(4,4)
rand_matrix

array([[100,  93,  59,  94],
       [ 51,  53,  68,  62],
       [ 73,  84,  97,  55],
       [ 84,  75,  85,  56]])

### Descriptive statistics for rand_matrix.

In [103]:
rand_matrix.mean()

74.3125

In [104]:
np.median(rand_matrix)

74.0

In [105]:
rand_matrix.max()-rand_matrix.min()  #range

49

In [107]:
rand_matrix.std()

16.483775166811757

In [108]:
rand_matrix.var()

271.71484375

In [109]:
q1 = np.percentile(rand_matrix,25)

In [110]:
q3 = np.percentile(rand_matrix,75)

In [111]:
IQR = q3-q1

In [113]:
lower = q1 - (1.5 * IQR)
upper = q3 + (1.5 * IQR)
rand_matrix[rand_matrix < lower]

array([], dtype=int32)

In [114]:
rand_matrix[rand_matrix > upper]

array([], dtype=int32)

**Analyze the Data:**

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]




Describe the data using numpy array.
Measure the following:

1.	How many employees are getting more less than 50000?

2.	Is it following Normal Distribution?

3.	What is the median salary?

4.	What is the range of salaries for this company?

5.	Find the salaries between average salary and 75% of salaries?

6.	How many employees are getting less than 25 % of salaries ?


In [125]:
salaries = np.array([87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638])

In [128]:
salaries[salaries < 50000]

array([31250, 39828, 41671, 34225, 32199])

salaries following Normal Distribution.

In [129]:
np.median(salaries)

61699.5

In [130]:
salaries.max() - salaries.min()   #range

3082388

In [133]:
avg = salaries.mean()
q1 = np.percentile(salaries,25)
q3 = np.percentile(salaries,75)

In [149]:
avg

166169.16666666666

In [150]:
q3

84496.5

In [151]:
salaries[(salaries > avg) & (salaries <= q3)]

array([], dtype=int32)

In [139]:
q1

52963.25

In [140]:
salaries[salaries < q1]

array([52453, 31250, 39828, 41671, 51428, 50477, 34225, 32199])

#### Finding the Outliers

In [141]:
IQR = q3-q1

In [143]:
lower = q1 - (1.5 * IQR)
upper = q3 + (1.5 * IQR)
lower

5663.375

In [144]:
upper

131796.375

In [145]:
salaries[salaries<lower]

array([], dtype=int32)

In [146]:
salaries[salaries>upper]

array([3113638])