1. clean the data(outlier,missing values,type conversion)


In [46]:
import numpy as np

In [68]:
data = np.genfromtxt(r"C:\Users\sathi\Downloads\Iris_clean_-_Copy.csv",dtype="float16",delimiter = ",")

In [69]:
data

array([[      nan,       nan,       nan,       nan],
       [5.102e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.699e+00, 3.199e+00, 1.300e+00, 2.000e-01],
       [4.602e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.398e+00,       nan, 1.700e+00, 3.999e-01],
       [4.602e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.398e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.100e+00,       nan, 9.998e-02],
       [5.398e+00, 3.699e+00, 1.500e+00, 2.000e-01],
       [4.801e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.801e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.301e+00, 3.000e+00, 1.100e+00, 9.998e-02],
       [5.801e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.699e+00, 4.398e+00, 1.500e+00, 3.999e-01],
       [5.041e+01,       nan, 1.300e+00, 3.999e-01],
       [5.102e+00, 3.500e+00, 1.400e+00, 3.000

In [70]:
sepal_length = data[1:,0]

In [71]:
sepal_length

array([  5.1,   4.9,   4.7,   4.6,  50. ,   5.4,   4.6,   5. ,   4.4,
         4.9,   5.4,   4.8,   4.8,   4.3,   5.8,   5.7,  50.4,   5.1,
         5.7,   5.1,   5.4,   5.1,   4.6,   5.1,   4.8,   5. ,   5. ,
         5.2,   5.2,   4.7,   4.8,   5.4,   5.2,   5.5,   4.9,   5. ,
         5.5,   4.9,   4.4,   5.1,   5. ,   4.5,   4.4,   5. ,   5.1,
         4.8,   5.1,   4.6,   5.3,   5. ,   7. ,   6.4,   6.9,   5.5,
         6.5,   5.7, 116.3,   4.9,   6.6,   5.2,   5. ,   5.9,   6. ,
         6.1,   5.6,   6.7,   5.6,   5.8,   6.2,   5.6,   5.9,   6.1,
         6.3,   6.1,   6.4,   6.6,   6.8,   6.7,   6. ,   5.7,   5.5,
         5.5,   5.8,   6. ,   5.4,   6. ,   6.7,   6.3,   5.6,   5.5,
         5.5,   6.1,   5.8,   5. ,   5.6,   5.7,   5.7,   6.2,   5.1,
         5.7,   6.3,   5.8,   7.1,   6.3,   6.5,   7.6,   4.9,   7.3,
         6.7,   7.2,   6.5,   6.4,   6.8,   5.7,   5.8,   6.4,   6.5,
         7.7,   7.7,   6. ,   6.9,   5.6,   7.7,   6.3,   6.7,   7.2,
         6.2,   6.1,

In [72]:
median = np.nanmedian(sepal_length)

In [73]:
median

5.8

In [74]:
sepal_length[sepal_length>6]

array([ 50. ,  50.4,   7. ,   6.4,   6.9,   6.5, 116.3,   6.6,   6.1,
         6.7,   6.2,   6.1,   6.3,   6.1,   6.4,   6.6,   6.8,   6.7,
         6.7,   6.3,   6.1,   6.2,   6.3,   7.1,   6.3,   6.5,   7.6,
         7.3,   6.7,   7.2,   6.5,   6.4,   6.8,   6.4,   6.5,   7.7,
         7.7,   6.9,   7.7,   6.3,   6.7,   7.2,   6.2,   6.1,   6.4,
        70.2,   6.4,   6.3,   6.1,   7.7,   6.3,   6.4,   6.9,   6.7,
         6.9,   6.8,   6.7,   6.7,   6.3,   6.5,   6.2,   7.7,   7.2,
         7.3,   6.7,   7.7,   6.3,   7.2,   6.5,   6.4], dtype=float16)

In [75]:
sepal_length = np.where(sepal_length>6,median,sepal_length)

In [76]:
sepal_length

array([5.1, 4.9, 4.7, 4.6, 5.8, 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.8, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 5.8, 5.8,
       5.8, 5.5, 5.8, 5.7, 5.8, 4.9, 5.8, 5.2, 5. , 5.9, 6. , 5.8, 5.6,
       5.8, 5.6, 5.8, 5.8, 5.6, 5.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 5.8, 5.8, 5.6, 5.5, 5.5,
       5.8, 5.8, 5. , 5.6, 5.7, 5.7, 5.8, 5.1, 5.7, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 4.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.7, 5.8, 5.8, 5.8,
       5.8, 5.8, 6. , 5.8, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       nan, nan, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 6. , 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.9, 5.6, 5.8, nan, nan, 5.8, 4.9,
       5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8], dtype=float16)

In [77]:
sepal_length = np.where(np.isnan(sepal_length),median,sepal_length)

In [78]:
sepal_length

array([5.1, 4.9, 4.7, 4.6, 5.8, 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.8, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 5.8, 5.8,
       5.8, 5.5, 5.8, 5.7, 5.8, 4.9, 5.8, 5.2, 5. , 5.9, 6. , 5.8, 5.6,
       5.8, 5.6, 5.8, 5.8, 5.6, 5.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 5.8, 5.8, 5.6, 5.5, 5.5,
       5.8, 5.8, 5. , 5.6, 5.7, 5.7, 5.8, 5.1, 5.7, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 4.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.7, 5.8, 5.8, 5.8,
       5.8, 5.8, 6. , 5.8, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 6. , 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8, 4.9,
       5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8], dtype=float16)

In [79]:
sepal_width = data[1:,1]

In [80]:
sepal_width

array([  3.5,   3. ,   3.2,   3.1,   3.6,   nan,   3.4,   3.4,   2.9,
         3.1,   3.7,   3.4, 130. ,   3. ,   4. ,   4.4,   nan,   3.5,
         3.8,   3.8,   3.4,   3.7,   3.6,   3.3,   3.4,   3. ,  34. ,
         3.5,   3.4,   3.2,   3.1,   3.4,   4.1,   4.2,   3.1,   3.2,
         3.5,   3.1,   3. ,   3.4,   3.5,   2.3,   3.2,   3.5,   3.8,
         3. ,   3.8,   3.2,   3.7,   3.3,   3.2,   3.2,   nan,   2.3,
         2.8,   2.8,   3.3,   2.4,   2.9,   2.7,   2. ,   3. ,   2.2,
         2.9,   2.9,   3.1,   3. ,   2.7,   2.2,   2.5,   3.2,   2.8,
         2.5,   nan,   2.9,   3. ,   2.8,   3. ,   2.9,   2.6,   2.4,
         2.4,   2.7,   2.7,   3. ,   3.4,   3.1,   2.3,   3. ,   2.5,
         2.6,   3. , 112.6,   2.3,   2.7,   3. ,   2.9,   2.9,   2.5,
         2.8,   3.3,   2.7,   3. ,   2.9,   3. ,   3. ,   2.5,   2.9,
         2.5,   3.6,   3.2,   2.7,   3. ,   2.5,   2.8,   3.2,   3. ,
         3.8,   2.6,   2.2,   3.2,   2.8,   2.8,   2.7,   3.3,   3.2,
         2.8,   3. ,

In [81]:
median = np.nanmedian(sepal_width)
median

3.0

In [82]:
sepal_width[sepal_width>3.4]

array([  3.5,   3.6,   3.7, 130. ,   4. ,   4.4,   3.5,   3.8,   3.8,
         3.7,   3.6,  34. ,   3.5,   4.1,   4.2,   3.5,   3.5,   3.5,
         3.8,   3.8,   3.7, 112.6,   3.6,   3.8,   3.8,   3.6],
      dtype=float16)

In [83]:
sepal_width = np.where(sepal_width>3.4,median,sepal_width)
sepal_width

array([3. , 3. , 3.2, 3.1, 3. , nan, 3.4, 3.4, 2.9, 3.1, 3. , 3.4, 3. ,
       3. , 3. , 3. , nan, 3. , 3. , 3. , 3.4, 3. , 3. , 3.3, 3.4, 3. ,
       3. , 3. , 3.4, 3.2, 3.1, 3.4, 3. , 3. , 3.1, 3.2, 3. , 3.1, 3. ,
       3.4, 3. , 2.3, 3.2, 3. , 3. , 3. , 3. , 3.2, 3. , 3.3, 3.2, 3.2,
       nan, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, nan, 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 3. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3. , 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3. , 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3. , 2.8, 2.8, 2.6, 3. , 3.4, nan, 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, nan, 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2, 2.5,
       2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3. , 3.2, 2.7], dtype=float16)

In [84]:
sepal_width = np.where(np.isnan(sepal_width),median,sepal_width)
sepal_width

array([3. , 3. , 3.2, 3.1, 3. , 3. , 3.4, 3.4, 2.9, 3.1, 3. , 3.4, 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3.4, 3. , 3. , 3.3, 3.4, 3. ,
       3. , 3. , 3.4, 3.2, 3.1, 3.4, 3. , 3. , 3.1, 3.2, 3. , 3.1, 3. ,
       3.4, 3. , 2.3, 3.2, 3. , 3. , 3. , 3. , 3.2, 3. , 3.3, 3.2, 3.2,
       3. , 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 3. , 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 3. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3. , 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3. , 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3. , 2.8, 2.8, 2.6, 3. , 3.4, 3. , 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2, 2.5,
       2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3. , 3.2, 2.7], dtype=float16)

In [97]:
petal_length = data[1:,2]
petal_length

array([ 1.4,  1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  nan,  1.5,
        1.6,  1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,  1.5,
        1. ,  1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,  1.5,
        1.4,  1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3, 13. ,  1.3,  1.6,
        1.9,  1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,  4.6,
        4.5,  4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,  4.4,
        4.5,  4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,  4.8,
        5. ,  4.5,  3.5, 13.8,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,  4.4,
        4.1,  4. ,  4.4,  nan,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,  3. ,
        4.1,  6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,  6.1,
        5.1,  5.3,  nan,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,  5.7,
        4.9,  6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,  nan,
        5.6,  5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  nan,  5.1,  5.1,
        5.9,  5.7,  nan,  5. ,  5.2,  5.4,  5.1,  4

In [98]:
median = np.nanmean(petal_length)
median

4.023

In [99]:
petal_length[petal_length>5]

array([13. , 13.8,  5.1,  6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  6.3,  5.8,
        6.1,  5.1,  5.3,  5.1,  5.3,  5.5,  6.7,  6.9,  5.7,  6.7,  5.7,
        6. ,  5.6,  5.8,  6.1,  5.6,  5.1,  5.6,  6.1,  5.6,  5.5,  5.4,
        5.1,  5.1,  5.9,  5.7,  5.2,  5.4,  5.1,  6.7,  5.7,  6. ,  6.3,
        5.8,  5.1,  6.7,  6.1,  5.1,  5.3], dtype=float16)

In [100]:
petal_length = np.where(petal_length>5,median,petal_length)
petal_length

array([1.4  , 1.4  , 1.3  , 1.5  , 1.4  , 1.7  , 1.4  , 1.5  , 1.4  ,
         nan, 1.5  , 1.6  , 1.4  , 1.1  , 1.2  , 1.5  , 1.3  , 1.4  ,
       1.7  , 1.5  , 1.7  , 1.5  , 1.   , 1.7  , 1.9  , 1.6  , 1.6  ,
       1.5  , 1.4  , 1.6  , 1.6  , 1.5  , 1.5  , 1.4  , 1.5  , 1.2  ,
       1.3  , 1.5  , 1.3  , 1.5  , 1.3  , 4.023, 1.3  , 1.6  , 1.9  ,
       1.4  , 1.6  , 1.4  , 1.5  , 1.4  , 4.7  , 4.5  , 4.9  , 4.   ,
       4.6  , 4.5  , 4.7  , 3.3  , 4.6  , 3.9  , 3.5  , 4.2  , 4.   ,
       4.7  , 3.6  , 4.4  , 4.5  , 4.1  , 4.5  , 3.9  , 4.8  , 4.   ,
       4.9  , 4.7  , 4.3  , 4.4  , 4.8  , 5.   , 4.5  , 3.5  , 4.023,
       3.7  , 3.9  , 4.023, 4.5  , 4.5  , 4.7  , 4.4  , 4.1  , 4.   ,
       4.4  ,   nan, 4.   , 3.3  , 4.2  , 4.2  , 4.2  , 4.3  , 3.   ,
       4.1  , 4.023, 4.023, 4.023, 4.023, 4.023, 4.023, 4.5  , 4.023,
       4.023, 4.023, 4.023, 4.023,   nan, 5.   , 4.023, 4.023, 4.023,
       4.023, 4.023, 5.   , 4.023, 4.9  , 4.023, 4.9  , 4.023, 4.023,
       4.8  , 4.9  ,

In [101]:
petal_length = np.where(np.isnan(petal_length),median,petal_length)
petal_length

array([1.4  , 1.4  , 1.3  , 1.5  , 1.4  , 1.7  , 1.4  , 1.5  , 1.4  ,
       4.023, 1.5  , 1.6  , 1.4  , 1.1  , 1.2  , 1.5  , 1.3  , 1.4  ,
       1.7  , 1.5  , 1.7  , 1.5  , 1.   , 1.7  , 1.9  , 1.6  , 1.6  ,
       1.5  , 1.4  , 1.6  , 1.6  , 1.5  , 1.5  , 1.4  , 1.5  , 1.2  ,
       1.3  , 1.5  , 1.3  , 1.5  , 1.3  , 4.023, 1.3  , 1.6  , 1.9  ,
       1.4  , 1.6  , 1.4  , 1.5  , 1.4  , 4.7  , 4.5  , 4.9  , 4.   ,
       4.6  , 4.5  , 4.7  , 3.3  , 4.6  , 3.9  , 3.5  , 4.2  , 4.   ,
       4.7  , 3.6  , 4.4  , 4.5  , 4.1  , 4.5  , 3.9  , 4.8  , 4.   ,
       4.9  , 4.7  , 4.3  , 4.4  , 4.8  , 5.   , 4.5  , 3.5  , 4.023,
       3.7  , 3.9  , 4.023, 4.5  , 4.5  , 4.7  , 4.4  , 4.1  , 4.   ,
       4.4  , 4.023, 4.   , 3.3  , 4.2  , 4.2  , 4.2  , 4.3  , 3.   ,
       4.1  , 4.023, 4.023, 4.023, 4.023, 4.023, 4.023, 4.5  , 4.023,
       4.023, 4.023, 4.023, 4.023, 4.023, 5.   , 4.023, 4.023, 4.023,
       4.023, 4.023, 5.   , 4.023, 4.9  , 4.023, 4.9  , 4.023, 4.023,
       4.8  , 4.9  ,

In [105]:
petal_width = data[1:,3]
petal_width

array([2.000e-01, 2.000e-01, 2.000e-01, 1.020e+01, 2.000e-01, 3.999e-01,
       3.000e-01, 2.000e-01, 2.000e-01, 9.998e-02, 2.000e-01, 2.000e-01,
       1.010e+01, 9.998e-02, 2.000e-01, 3.999e-01, 3.999e-01, 3.000e-01,
       3.000e-01, 3.000e-01, 2.000e-01, 3.999e-01, 2.000e-01, 5.000e-01,
       2.000e-01, 2.000e-01, 3.999e-01, 2.000e-01, 1.102e+02, 2.000e-01,
       2.000e-01, 3.999e-01, 9.998e-02, 2.000e-01, 9.998e-02, 2.000e-01,
       2.000e-01, 9.998e-02, 2.000e-01, 2.000e-01, 3.000e-01, 3.000e-01,
       2.000e-01, 6.001e-01, 3.999e-01, 3.000e-01, 2.000e-01, 2.000e-01,
       2.000e-01, 2.000e-01, 1.400e+00, 1.500e+00, 1.500e+00, 1.300e+00,
       1.500e+00, 1.300e+00, 1.600e+00, 1.600e+01, 1.300e+00, 1.400e+00,
       1.000e+00, 1.500e+00, 1.000e+00, 1.400e+00, 1.300e+00, 1.400e+00,
       1.500e+00, 1.000e+00, 1.500e+00, 1.100e+00, 1.800e+00, 1.300e+00,
       1.500e+00, 1.200e+00, 1.300e+00, 1.400e+00, 1.400e+00, 1.700e+00,
       1.500e+00, 1.000e+00, 1.100e+00, 1.000e+00, 

In [106]:
median = np.nanmedian(petal_width)
median

1.5

In [107]:
petal_width[petal_width>2]

array([ 10.2,  10.1, 110.2,  16. , 111.1,   2.5,   2.1,   2.2,   2.1,
         2.5,   2.1,   2.4,   2.3,   2.2,   2.3,   2.3,   2.1,   2.1,
         2.2,   2.3,   2.4,   2.1,   2.4,   2.3,   2.3,   2.5,   2.3,
         2.3,   2.1,   2.5], dtype=float16)

In [108]:
petal_width = np.where(petal_width>2,median,petal_width)
petal_width

array([0.2, 0.2, 0.2, 1.5, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 1.5,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 1.5, 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1.5, 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.5, 1.3, 1.5, 1.9, 1.5, 1.8,
       1.5, 1.5, 1.7, 1.8, 1.8, 1.5, 2. , 1.9, 1.5, 2. , 1.5, 1.5, 1.8,
       1.5, 1.5, 1.5, 1.5, 2. , 2. , 1.8, 1.5, 1.8, 1.8, 1.8, 1.5, 1.6,
       1.9, 2. , 1.5, 1.5, 1.4, 1.5, 1.5, 1.8, 1.8, 1.5, 1.5, 1.5, 1.9,
       1.5, 1.5, 1.5, 1.9, 2. , 1.5, 1.8, 2. , 2. , 1.8, 1.5, 1.8, 1.7,
       1.8, 1.8, 1.8, 2. , 2. , 1.8, 1.5, 2. , 1.9], dtype=float16)

In [109]:
petal_width = np.where(np.isnan(petal_width),median,petal_width)
petal_width

array([0.2, 0.2, 0.2, 1.5, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 1.5,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 1.5, 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1.5, 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.5, 1.3, 1.5, 1.9, 1.5, 1.8,
       1.5, 1.5, 1.7, 1.8, 1.8, 1.5, 2. , 1.9, 1.5, 2. , 1.5, 1.5, 1.8,
       1.5, 1.5, 1.5, 1.5, 2. , 2. , 1.8, 1.5, 1.8, 1.8, 1.8, 1.5, 1.6,
       1.9, 2. , 1.5, 1.5, 1.4, 1.5, 1.5, 1.8, 1.8, 1.5, 1.5, 1.5, 1.9,
       1.5, 1.5, 1.5, 1.9, 2. , 1.5, 1.8, 2. , 2. , 1.8, 1.5, 1.8, 1.7,
       1.8, 1.8, 1.8, 2. , 2. , 1.8, 1.5, 2. , 1.9], dtype=float16)

2. What is the mean value of sepal length


In [112]:
sepal_length.mean()

5.52

3. sort the sepal width in ascending order.


In [119]:
np.sort(sepal_width)

array([2. , 2.2, 2.2, 2.2, 2.3, 2.3, 2.3, 2.3, 2.4, 2.4, 2.4, 2.5, 2.5,
       2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.6, 2.6, 2.6, 2.6, 2.7,
       2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.8, 2.8,
       2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8,
       2.8, 2.8, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1,
       3.1, 3.1, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2,
       3.2, 3.2, 3.2, 3.2, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.4, 3.4,
       3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4], dtype=float16)

4. apply all statistical measures on  sepal width and length


### Statistical Measures on SepalWidth

In [176]:
sepal_width

array([2. , 2.2, 2.2, 2.2, 2.3, 2.3, 2.3, 2.3, 2.4, 2.4, 2.4, 2.5, 2.5,
       2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.6, 2.6, 2.6, 2.6, 2.7,
       2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.8, 2.8,
       2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8,
       2.8, 2.8, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1,
       3.1, 3.1, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2,
       3.2, 3.2, 3.2, 3.2, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.4, 3.4,
       3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4], dtype=float16)

In [177]:
sepal_width.mean()

2.926

In [178]:
np.median(sepal_width)

3.0

In [179]:
range = np.max(sepal_width)-np.min(sepal_width)
range

1.4

In [180]:
q3 = np.quantile(sepal_width,0.75)
q3

3.099609375

In [181]:
q1 = np.quantile(sepal_width,0.25)
q1

2.80078125

In [182]:
IQR = q3-q1

In [183]:
lower = q1 - (1.5*IQR)
upper = q3 + (1.5*IQR)
lower

2.3525390625

In [190]:
sepal_width[sepal_width<lower]

array([], dtype=float16)

In [185]:
sepal_width[sepal_width>upper]

array([], dtype=float16)

In [186]:
np.var(sepal_width)

0.0797

In [187]:
np.std(sepal_width)

0.2822

### Statistical Measures on SepalLength

In [150]:
sepal_length

array([5.1, 4.9, 4.7, 4.6, 5.8, 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.8, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 5.8, 5.8,
       5.8, 5.5, 5.8, 5.7, 5.8, 4.9, 5.8, 5.2, 5. , 5.9, 6. , 5.8, 5.6,
       5.8, 5.6, 5.8, 5.8, 5.6, 5.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 5.8, 5.8, 5.6, 5.5, 5.5,
       5.8, 5.8, 5. , 5.6, 5.7, 5.7, 5.8, 5.1, 5.7, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 4.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.7, 5.8, 5.8, 5.8,
       5.8, 5.8, 6. , 5.8, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 6. , 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8, 4.9,
       5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8], dtype=float16)

In [151]:
sepal_length.mean()

5.52

In [152]:
np.median(sepal_length)

5.8

In [154]:
range = np.max(sepal_length) - np.min(sepal_length)
range

1.699

In [155]:
q1 = np.quantile(sepal_length,0.25)


In [164]:
q3 = np.quantile(sepal_length,0.75)
q3

5.80078125

In [165]:
IQR = q3 - q1

In [166]:
lower = q1 - (1.5 * IQR)
upper = q3 - (1.5 * IQR)
upper

4.8984375

In [172]:
sepal_length[sepal_length<lower]

array([], dtype=float16)

In [175]:
sepal_length[sepal_length>upper]

array([], dtype=float16)

In [191]:
np.var(sepal_length)

0.1788

In [192]:
np.std(sepal_length)

0.4229

5. after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values

In [193]:
np.savez("cleaned.npz",sepal_length,sepal_width,petal_length,petal_width)

In [202]:
a = np.load("cleaned.npz")

In [205]:
a.files

['arr_0', 'arr_1', 'arr_2', 'arr_3']

In [207]:
a['arr_0'] #sepal_length

array([5.1, 4.9, 4.7, 4.6, 5.8, 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.8, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 5.8, 5.8,
       5.8, 5.5, 5.8, 5.7, 5.8, 4.9, 5.8, 5.2, 5. , 5.9, 6. , 5.8, 5.6,
       5.8, 5.6, 5.8, 5.8, 5.6, 5.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 5.8, 5.8, 5.6, 5.5, 5.5,
       5.8, 5.8, 5. , 5.6, 5.7, 5.7, 5.8, 5.1, 5.7, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 4.9, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.7, 5.8, 5.8, 5.8,
       5.8, 5.8, 6. , 5.8, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 6. , 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8, 4.9,
       5.8, 5.8, 5.9, 5.6, 5.8, 5.8, 5.8, 5.8, 5.8], dtype=float16)

In [208]:
a['arr_1'] #sepal_width

array([2. , 2.2, 2.2, 2.2, 2.3, 2.3, 2.3, 2.3, 2.4, 2.4, 2.4, 2.5, 2.5,
       2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.6, 2.6, 2.6, 2.6, 2.7,
       2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.8, 2.8,
       2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8,
       2.8, 2.8, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1,
       3.1, 3.1, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2,
       3.2, 3.2, 3.2, 3.2, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.4, 3.4,
       3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4], dtype=float16)

In [209]:
a['arr_2'] #petal_length

array([1.4  , 1.4  , 1.3  , 1.5  , 1.4  , 1.7  , 1.4  , 1.5  , 1.4  ,
       4.023, 1.5  , 1.6  , 1.4  , 1.1  , 1.2  , 1.5  , 1.3  , 1.4  ,
       1.7  , 1.5  , 1.7  , 1.5  , 1.   , 1.7  , 1.9  , 1.6  , 1.6  ,
       1.5  , 1.4  , 1.6  , 1.6  , 1.5  , 1.5  , 1.4  , 1.5  , 1.2  ,
       1.3  , 1.5  , 1.3  , 1.5  , 1.3  , 4.023, 1.3  , 1.6  , 1.9  ,
       1.4  , 1.6  , 1.4  , 1.5  , 1.4  , 4.7  , 4.5  , 4.9  , 4.   ,
       4.6  , 4.5  , 4.7  , 3.3  , 4.6  , 3.9  , 3.5  , 4.2  , 4.   ,
       4.7  , 3.6  , 4.4  , 4.5  , 4.1  , 4.5  , 3.9  , 4.8  , 4.   ,
       4.9  , 4.7  , 4.3  , 4.4  , 4.8  , 5.   , 4.5  , 3.5  , 4.023,
       3.7  , 3.9  , 4.023, 4.5  , 4.5  , 4.7  , 4.4  , 4.1  , 4.   ,
       4.4  , 4.023, 4.   , 3.3  , 4.2  , 4.2  , 4.2  , 4.3  , 3.   ,
       4.1  , 4.023, 4.023, 4.023, 4.023, 4.023, 4.023, 4.5  , 4.023,
       4.023, 4.023, 4.023, 4.023, 4.023, 5.   , 4.023, 4.023, 4.023,
       4.023, 4.023, 5.   , 4.023, 4.9  , 4.023, 4.9  , 4.023, 4.023,
       4.8  , 4.9  ,

In [210]:
a['arr_3'] #petal_width

array([0.2, 0.2, 0.2, 1.5, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 1.5,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 1.5, 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1.5, 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.5, 1.3, 1.5, 1.9, 1.5, 1.8,
       1.5, 1.5, 1.7, 1.8, 1.8, 1.5, 2. , 1.9, 1.5, 2. , 1.5, 1.5, 1.8,
       1.5, 1.5, 1.5, 1.5, 2. , 2. , 1.8, 1.5, 1.8, 1.8, 1.8, 1.5, 1.6,
       1.9, 2. , 1.5, 1.5, 1.4, 1.5, 1.5, 1.8, 1.8, 1.5, 1.5, 1.5, 1.9,
       1.5, 1.5, 1.5, 1.9, 2. , 1.5, 1.8, 2. , 2. , 1.8, 1.5, 1.8, 1.7,
       1.8, 1.8, 1.8, 2. , 2. , 1.8, 1.5, 2. , 1.9], dtype=float16)